/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/identity/{applicant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch Identity */
        get: operations["fetch_identity_identity__applicant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/{applicant_id}/mismatches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Mismatch */
        get: operations["check_mismatch_identity__applicant_id__mismatches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Match Video */
        post: operations["match_video_match_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Mismatch */
        Mismatch: {
            /** Field */
            field: string;
            /** Fetched Value */
            fetched_value: string;
            /** Issue */
            issue: string;
            /** Suggested Fix */
            suggested_fix: string;
        };
        /** MismatchCheckResult */
        MismatchCheckResult: {
            /** Applicant Id */
            applicant_id: string;
            /** Mismatches */
            mismatches: components["schemas"]["Mismatch"][];
            /** Clear To Submit */
            clear_to_submit: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedProfile */
        VerifiedProfile: {
            /** Applicant Id */
            applicant_id: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Address */
            address: string;
            /** Photo Url */
            photo_url: string;
            /** Gps Suggested Rto */
            gps_suggested_rto?: string | null;
            /** Aadhaar Registered Address */
            aadhaar_registered_address?: string | null;
            /** Addresses Match */
            addresses_match?: boolean | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
        /** VideoMatchRequest */
        VideoMatchRequest: {
            /** Applicant Id */
            applicant_id: string;
            /** Query */
            query: string;
            /** Journey Stage */
            journey_stage?: string | null;
        };
        /** VideoMatchResult */
        VideoMatchResult: {
            /** Video Id */
            video_id: string;
            /** Topic */
            topic: string;
            /** Confidence */
            confidence: number;
            /** Fallback Message */
            fallback_message?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    fetch_identity_identity__applicant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_mismatch_identity__applicant_id__mismatches_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MismatchCheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    match_video_match_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoMatchResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
