/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gov/ll-applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Ll Application */
        post: operations["submit_ll_application_gov_ll_applications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gov/applications/{application_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Application Status */
        get: operations["get_application_status_gov_applications__application_number__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gov/applications/{application_number}/verify-documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Documents
         * @description Mock RTO-side document verification.
         *
         *     With real Sarathi access this becomes an inbound status we poll or receive;
         *     the mock exposes it as an action so the journey can be exercised end to end.
         */
        post: operations["verify_documents_gov_applications__application_number__verify_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gov/dl-test/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Dl Test Slots */
        get: operations["list_dl_test_slots_gov_dl_test_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gov/dl-test/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Dl Test */
        post: operations["book_dl_test_gov_dl_test_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gov/test-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Report Test Result
         * @description Record an LL or DL test outcome (mock stand-in for the RTO reporting it).
         */
        post: operations["report_test_result_gov_test_results_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** GovApplicationStatus */
        GovApplicationStatus: {
            /** Application Number */
            application_number: string;
            /** Applicant Id */
            applicant_id: string;
            /** Stage */
            stage: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Failed Checkpoint */
            failed_checkpoint?: string | null;
            /** Integrity Tier */
            integrity_tier?: string | null;
        };
        /** GovSubmissionResult */
        GovSubmissionResult: {
            /** Application Number */
            application_number: string;
            /** Status */
            status: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LLApplicationSubmission */
        LLApplicationSubmission: {
            /** Applicant Id */
            applicant_id: string;
            /** Name */
            name: string;
            /** Dob */
            dob: string;
            /** Address */
            address: string;
            /** Photo Url */
            photo_url: string;
            /** Rto Code */
            rto_code: string;
            /**
             * Vehicle Class
             * @default LMV
             */
            vehicle_class: string;
        };
        /** SlotBookingRequest */
        SlotBookingRequest: {
            /** Applicant Id */
            applicant_id: string;
            /** Application Number */
            application_number: string;
            /** Slot Id */
            slot_id: string;
        };
        /** SlotBookingResult */
        SlotBookingResult: {
            /** Booking Id */
            booking_id: string;
            slot: components["schemas"]["TestSlot"];
            /** Confirmed */
            confirmed: boolean;
        };
        /** TestResultReport */
        TestResultReport: {
            /** Application Number */
            application_number: string;
            /** Test Type */
            test_type: string;
            /** Passed */
            passed: boolean;
            /** Failed Checkpoint */
            failed_checkpoint?: string | null;
            /** Integrity Score */
            integrity_score?: number | null;
            /** Integrity Tier */
            integrity_tier?: string | null;
            /** Integrity Events */
            integrity_events?: number | null;
        };
        /** TestSlot */
        TestSlot: {
            /** Slot Id */
            slot_id: string;
            /** Rto Code */
            rto_code: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Capacity Left */
            capacity_left: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    submit_ll_application_gov_ll_applications_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LLApplicationSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovSubmissionResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_application_status_gov_applications__application_number__get: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovApplicationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_documents_gov_applications__application_number__verify_documents_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovApplicationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_dl_test_slots_gov_dl_test_slots_get: {
        parameters: {
            query: {
                rto_code: string;
            };
            header?: {
                "x-service-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSlot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_dl_test_gov_dl_test_bookings_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SlotBookingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotBookingResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_test_result_gov_test_results_post: {
        parameters: {
            query?: never;
            header?: {
                "x-service-token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestResultReport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GovApplicationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
