/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Personas
         * @description List available mock citizen personas for testing.
         */
        get: operations["list_personas_identity_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/fetch/{applicant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch Identity
         * @description Fetch verified profile from DigiLocker / Aadhaar e-KYC.
         */
        get: operations["fetch_identity_identity_fetch__applicant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/identity/mismatch-check/{applicant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Mismatch
         * @description Check for data discrepancies and rejection prevention before submission.
         */
        get: operations["check_mismatch_identity_mismatch_check__applicant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Mismatch */
        Mismatch: {
            /** Field */
            field: string;
            /** Fetched Value */
            fetched_value: string;
            /** Issue */
            issue: string;
            /** Suggested Fix */
            suggested_fix: string;
            /**
             * Severity
             * @description "error" (blocks submission) or "warning"
             * @default error
             */
            severity: string;
        };
        /** MismatchCheckResult */
        MismatchCheckResult: {
            /** Applicant Id */
            applicant_id: string;
            /** Mismatches */
            mismatches: components["schemas"]["Mismatch"][];
            /** Clear To Submit */
            clear_to_submit: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedProfile */
        VerifiedProfile: {
            /**
             * Applicant Id
             * @description Stable identifier for a citizen across all modules
             */
            applicant_id: string;
            /**
             * Source
             * @description "digilocker_aadhaar" | "pan" | "manual"
             */
            source: string;
            /** Name */
            name: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Address */
            address: string;
            /** Photo Url */
            photo_url: string;
            /**
             * Gps Suggested Rto
             * @description Suggested nearest RTO based on GPS/device location (convenience only)
             */
            gps_suggested_rto?: string | null;
            /**
             * Aadhaar Registered Address
             * @description Aadhaar-registered address determining legal RTO jurisdiction
             */
            aadhaar_registered_address?: string | null;
            /**
             * Addresses Match
             * @description True if GPS location matches Aadhaar registered jurisdiction, False otherwise
             */
            addresses_match?: boolean | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Age
             * @description Computed age in years
             */
            age?: number | null;
            /**
             * Age Eligible
             * @description True if age >= 18 for first-time car driving licence
             */
            age_eligible?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_personas_identity_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    fetch_identity_identity_fetch__applicant_id__get: {
        parameters: {
            query?: {
                /** @description Optional GPS/device location suggested nearest RTO */
                gps_suggested_rto?: string | null;
            };
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_mismatch_identity_mismatch_check__applicant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MismatchCheckResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
