/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Bind a browser session to one applicant_id (the demo's stand-in for login).
         *
         *     In production this would follow a real OTP/Aadhaar auth; here it mints the
         *     session so every subsequent /journey call is ownership-checked. The prototype
         *     posture (no OTP verification behind it) is documented in the README.
         */
        post: operations["create_session_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Journey
         * @description What's next — the AGENTS.md §7.4 response.
         */
        get: operations["get_journey_journey__applicant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Event */
        post: operations["report_event_journey__applicant_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/verified-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verified Profile
         * @description Module 2's integrated view of Module 3: what is already verified.
         */
        get: operations["verified_profile_journey__applicant_id__verified_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply
         * @description Zero-form application: verified identity in, LL application out.
         */
        post: operations["apply_journey__applicant_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Journey
         * @description Demo reset: forget this journey so the persona can be walked again.
         *
         *     Demo personas are shared records; without this, one visitor completing a
         *     journey consumes the persona for everyone until a restart.
         */
        post: operations["reset_journey_journey__applicant_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Poll the government side (through Module 5) and fold its status in.
         */
        post: operations["sync_journey__applicant_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/dl-test/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dl Test Slots */
        get: operations["dl_test_slots_journey__applicant_id__dl_test_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/dl-test/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Dl Test */
        post: operations["book_dl_test_journey__applicant_id__dl_test_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/ll-exam": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ll Exam
         * @description The exam paper with the answer key stripped.
         */
        get: operations["get_ll_exam_journey__applicant_id__ll_exam_get"];
        put?: never;
        /** Submit Ll Exam */
        post: operations["submit_ll_exam_journey__applicant_id__ll_exam_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/simulate/dl-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate Dl Result
         * @description Demo stand-in for the RTO reporting a physical driving-test outcome.
         *
         *     Routed through Module 2 (token-checked) so the browser never touches the
         *     government endpoints directly. In production this is an inbound RTO signal.
         */
        post: operations["simulate_dl_result_journey__applicant_id__simulate_dl_result_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyRequest */
        ApplyRequest: {
            /** Confirmed Rto Code */
            confirmed_rto_code?: string | null;
        };
        /** BookingRequest */
        BookingRequest: {
            /** Slot Id */
            slot_id: string;
        };
        /** Certainty */
        Certainty: {
            /** Cost Inr */
            cost_inr: number;
            /** Eta Days */
            eta_days: number;
            /** Visit Count */
            visit_count: number;
        };
        /** DlResultRequest */
        DlResultRequest: {
            /** Passed */
            passed: boolean;
            /** Failed Checkpoint */
            failed_checkpoint?: string | null;
        };
        /** EventRequest */
        EventRequest: {
            /** Event */
            event: string;
        };
        /** ExamOutcome */
        ExamOutcome: {
            result: components["schemas"]["ExamResult"];
            state: components["schemas"]["JourneyState"];
        };
        /** ExamPaper */
        ExamPaper: {
            /** Questions */
            questions: components["schemas"]["ExamQuestion"][];
            /** Pass Mark */
            pass_mark: number;
            /** Total */
            total: number;
        };
        /** ExamQuestion */
        ExamQuestion: {
            /** Id */
            id: string;
            /** Prompt */
            prompt: string;
            /** Options */
            options: string[];
            /** Icon */
            icon?: string | null;
        };
        /** ExamResult */
        ExamResult: {
            /** Passed */
            passed: boolean;
            /** Score */
            score: number;
            /** Total */
            total: number;
            /** Outcomes */
            outcomes: components["schemas"]["QuestionOutcome"][];
            /** Integrity Score */
            integrity_score: number;
            /** Integrity Tier */
            integrity_tier: string;
        };
        /** ExamSubmission */
        ExamSubmission: {
            /** Answers */
            answers: (number | null)[];
            integrity?: components["schemas"]["IntegritySubmission"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IntegritySubmission */
        IntegritySubmission: {
            /**
             * Camera
             * @default unavailable
             */
            camera: string;
            /**
             * Events
             * @default []
             */
            events: {
                [key: string]: unknown;
            }[];
        };
        /**
         * JourneyStage
         * @description Stable journey stages for the first-time car licence journey.
         * @enum {string}
         */
        JourneyStage: "no_licence" | "ll_application_submitted" | "ll_documents_verified" | "ll_test_scheduled" | "ll_issued" | "practice_window" | "dl_test_booked" | "dl_test_result_fail" | "dl_test_result_pass" | "dl_issued";
        /** JourneyState */
        JourneyState: {
            /** Applicant Id */
            applicant_id: string;
            /**
             * Journey Type
             * @default first_time_licence
             */
            journey_type: string;
            current_stage: components["schemas"]["JourneyStage"];
            next_action: components["schemas"]["NextAction"];
            certainty: components["schemas"]["Certainty"];
            /**
             * Required Documents
             * @default []
             */
            required_documents: components["schemas"]["RequiredDocument"][];
            /** Stage Detail */
            stage_detail?: string | null;
            /** Application Number */
            application_number?: string | null;
        };
        /** Mismatch */
        Mismatch: {
            /** Field */
            field: string;
            /** Fetched Value */
            fetched_value: string;
            /** Issue */
            issue: string;
            /** Suggested Fix */
            suggested_fix: string;
            /**
             * Severity
             * @description "error" (blocks submission) or "warning"
             * @default error
             */
            severity: string;
        };
        /** MismatchCheckResult */
        MismatchCheckResult: {
            /** Applicant Id */
            applicant_id: string;
            /** Mismatches */
            mismatches: components["schemas"]["Mismatch"][];
            /** Clear To Submit */
            clear_to_submit: boolean;
        };
        /** NextAction */
        NextAction: {
            /** Type */
            type: string;
            /** Label */
            label: string;
        };
        /** QuestionOutcome */
        QuestionOutcome: {
            /** Id */
            id: string;
            /** Correct Index */
            correct_index: number;
            /** Was Correct */
            was_correct: boolean;
            /** Explanation */
            explanation: string;
        };
        /** RequiredDocument */
        RequiredDocument: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /**
             * Satisfied By Ekyc
             * @default false
             */
            satisfied_by_ekyc: boolean;
        };
        /** SessionRequest */
        SessionRequest: {
            /** Applicant Id */
            applicant_id: string;
        };
        /** SessionResponse */
        SessionResponse: {
            /** Token */
            token: string;
            /** Applicant Id */
            applicant_id: string;
            /** Expires In */
            expires_in: number;
        };
        /** TestSlot */
        TestSlot: {
            /** Slot Id */
            slot_id: string;
            /** Rto Code */
            rto_code: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Capacity Left */
            capacity_left: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedIdentityView */
        VerifiedIdentityView: {
            profile: components["schemas"]["VerifiedProfile"];
            mismatch_check: components["schemas"]["MismatchCheckResult"];
            /**
             * Blocking Mismatches
             * @default []
             */
            blocking_mismatches: components["schemas"]["Mismatch"][];
            /**
             * Advisory Mismatches
             * @default []
             */
            advisory_mismatches: components["schemas"]["Mismatch"][];
            /**
             * Clear To Submit
             * @default true
             */
            clear_to_submit: boolean;
            /** Gps Rto Choice */
            gps_rto_choice?: string | null;
            /** Aadhaar Rto Choice */
            aadhaar_rto_choice?: string | null;
        };
        /** VerifiedProfile */
        VerifiedProfile: {
            /**
             * Applicant Id
             * @description Stable identifier for a citizen across all modules
             */
            applicant_id: string;
            /**
             * Source
             * @description "digilocker_aadhaar" | "pan" | "manual"
             */
            source: string;
            /** Name */
            name: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Address */
            address: string;
            /** Photo Url */
            photo_url: string;
            /**
             * Gps Suggested Rto
             * @description Suggested nearest RTO based on GPS/device location (convenience only)
             */
            gps_suggested_rto?: string | null;
            /**
             * Aadhaar Registered Address
             * @description Aadhaar-registered address determining legal RTO jurisdiction
             */
            aadhaar_registered_address?: string | null;
            /**
             * Addresses Match
             * @description True if GPS location matches Aadhaar registered jurisdiction, False otherwise
             */
            addresses_match?: boolean | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Age
             * @description Computed age in years
             */
            age?: number | null;
            /**
             * Age Eligible
             * @description True if age >= 18 for first-time car driving licence
             */
            age_eligible?: boolean | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_journey_journey__applicant_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_event_journey__applicant_id__events_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verified_profile_journey__applicant_id__verified_profile_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedIdentityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_journey__applicant_id__apply_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_journey_journey__applicant_id__reset_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_journey__applicant_id__sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dl_test_slots_journey__applicant_id__dl_test_slots_get: {
        parameters: {
            query?: {
                rto_code?: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSlot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_dl_test_journey__applicant_id__dl_test_bookings_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ll_exam_journey__applicant_id__ll_exam_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamPaper"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_ll_exam_journey__applicant_id__ll_exam_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSubmission"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamOutcome"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_dl_result_journey__applicant_id__simulate_dl_result_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DlResultRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
