/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Journey
         * @description What's next — the AGENTS.md §7.4 response.
         */
        get: operations["get_journey_journey__applicant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Event */
        post: operations["report_event_journey__applicant_id__events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/verified-profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verified Profile
         * @description Module 2's integrated view of Module 3: what is already verified.
         */
        get: operations["verified_profile_journey__applicant_id__verified_profile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply
         * @description Zero-form application: verified identity in, LL application out.
         */
        post: operations["apply_journey__applicant_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync
         * @description Poll the government side (through Module 5) and fold its status in.
         */
        post: operations["sync_journey__applicant_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/dl-test/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dl Test Slots */
        get: operations["dl_test_slots_journey__applicant_id__dl_test_slots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/journey/{applicant_id}/dl-test/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Dl Test */
        post: operations["book_dl_test_journey__applicant_id__dl_test_bookings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApplyRequest */
        ApplyRequest: {
            /** Confirmed Rto Code */
            confirmed_rto_code?: string | null;
        };
        /** BookingRequest */
        BookingRequest: {
            /** Slot Id */
            slot_id: string;
        };
        /** Certainty */
        Certainty: {
            /** Cost Inr */
            cost_inr: number;
            /** Eta Days */
            eta_days: number;
            /** Visit Count */
            visit_count: number;
        };
        /** EventRequest */
        EventRequest: {
            /** Event */
            event: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JourneyStage
         * @enum {string}
         */
        JourneyStage: "no_licence" | "ll_application_submitted" | "ll_documents_verified" | "ll_test_scheduled" | "ll_issued" | "practice_window" | "dl_test_booked" | "dl_test_result_fail" | "dl_test_result_pass" | "dl_issued";
        /** JourneyState */
        JourneyState: {
            /** Applicant Id */
            applicant_id: string;
            /**
             * Journey Type
             * @default first_time_licence
             */
            journey_type: string;
            current_stage: components["schemas"]["JourneyStage"];
            next_action: components["schemas"]["NextAction"];
            certainty: components["schemas"]["Certainty"];
            /**
             * Required Documents
             * @default []
             */
            required_documents: components["schemas"]["RequiredDocument"][];
            /** Stage Detail */
            stage_detail?: string | null;
            /** Application Number */
            application_number?: string | null;
        };
        /** Mismatch */
        Mismatch: {
            /** Field */
            field: string;
            /** Fetched Value */
            fetched_value: string;
            /** Issue */
            issue: string;
            /** Suggested Fix */
            suggested_fix: string;
        };
        /** MismatchCheckResult */
        MismatchCheckResult: {
            /** Applicant Id */
            applicant_id: string;
            /** Mismatches */
            mismatches: components["schemas"]["Mismatch"][];
            /** Clear To Submit */
            clear_to_submit: boolean;
        };
        /** NextAction */
        NextAction: {
            /** Type */
            type: string;
            /** Label */
            label: string;
        };
        /** RequiredDocument */
        RequiredDocument: {
            /** Code */
            code: string;
            /** Label */
            label: string;
            /**
             * Satisfied By Ekyc
             * @default false
             */
            satisfied_by_ekyc: boolean;
        };
        /** TestSlot */
        TestSlot: {
            /** Slot Id */
            slot_id: string;
            /** Rto Code */
            rto_code: string;
            /**
             * Starts At
             * Format: date-time
             */
            starts_at: string;
            /** Capacity Left */
            capacity_left: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedIdentityView */
        VerifiedIdentityView: {
            profile: components["schemas"]["VerifiedProfile"];
            mismatch_check: components["schemas"]["MismatchCheckResult"];
        };
        /** VerifiedProfile */
        VerifiedProfile: {
            /** Applicant Id */
            applicant_id: string;
            /** Source */
            source: string;
            /** Name */
            name: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /** Address */
            address: string;
            /** Photo Url */
            photo_url: string;
            /** Gps Suggested Rto */
            gps_suggested_rto?: string | null;
            /** Aadhaar Registered Address */
            aadhaar_registered_address?: string | null;
            /** Addresses Match */
            addresses_match?: boolean | null;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_journey_journey__applicant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_event_journey__applicant_id__events_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verified_profile_journey__applicant_id__verified_profile_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedIdentityView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_journey__applicant_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_journey__applicant_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dl_test_slots_journey__applicant_id__dl_test_slots_get: {
        parameters: {
            query?: {
                rto_code?: string;
            };
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestSlot"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    book_dl_test_journey__applicant_id__dl_test_bookings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicant_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JourneyState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
